version: "3.8"

networks:
  nginx_network:
    external: true
  internal:
    driver: overlay
    name: 'global'
    attachable: true
services:
  npm:
    image: node:12.18.1
  app:
    image: kooldev/php:8.1
    container_name: ozodbek-app
    working_dir: /app
    restart: always
    networks:
      - internal
      - nginx_network
    volumes:
      - '.:/app'
      - './docker/php/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
    links:
      - app-database
    depends_on:
      - app-database
  app-nginx:
    image: nginx:alpine
    container_name: Chirper-app-nginx
    restart: always
    working_dir: /app
    networks:
      - internal
      - nginx_network
    ports:
      - "9002:80"
    volumes:
      - .:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - "app"
  app-composer:
    image: composer:latest
    container_name: Chirper-app-composer
    working_dir: /app
    command: update --ignore-platform-reqs
    volumes:
      - .:/app
    restart: on-failure
    depends_on:
      - app
  app-database:
    image: mariadb:latest
    restart: always
    container_name: Chirper-app-database
    working_dir: /app
    networks:
      - internal
      - nginx_network
    environment:
      - MYSQL_ROOT_PASSWORD=9ZpmkdKLyqm4MGGtP3LAv
      - MYSQL_DATABASE=app
      - MYSQL_USER=xonsaroy
      - MYSQL_PASSWORD=J5F9qb4YUNjkAhuGTfa2C
    volumes:
      - .:/app
      - ./app-database:/var/lib/mysql
    ports:
      - '8000:3306'
volumes:
  app-database:
    driver: local


